<?xml version="1.0"?>
<!-- BOTTOM FIXED LINK 
This link is the base of the arm in which arm is placed 
-->
<robot name="six_dof_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Include Gazebo Properties-->
<xacro:include filename="$(find robotarm_description)/urdf/robotArm.gazebo.xacro" />

<!-- Include materials -->

    <material name="Blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>

    <material name="Red">
        <color rgba="0.8 0.0 0.0 1.0"/>
</material>

<material name="White">
    <color rgba="1 1 1 1"/>
  </material>

<!-- Constants -->
<property name="M_PI" value="3.14159"/>


 <!-- base_link Properties -->
  <property name="base_link_width" value="0.5" />
  <property name="base_link_depth" value="0.06" />
  <property name="base_link_height" value="1" />

  <property name="base_link2_height" value = "0.02" />

 <!-- Shoulder pan link properties -->
  <property name="shoulder_pan_width" value="0.04" />
  <property name="shoulder_pan_len" value="0.02" />


  <!-- Shoulder pitch link properties -->
  <property name="shoulder_pitch_len" value="0.14" />
  <property name="shoulder_pitch_width" value="0.04" />
  <property name="shoulder_pitch_height" value="0.04" />


  <!-- Elbow roll link properties -->
  <property name="elbow_roll_width" value="0.02" />
  <property name="elbow_roll_len" value="0.06" />


  <!-- Elbow pitch link properties -->
  <property name="elbow_pitch_len" value="0.22" />
  <property name="elbow_pitch_width" value="0.04" />
  <property name="elbow_pitch_height" value="0.04" />


  <!-- Wrist roll link properties -->
  <property name="wrist_roll_width" value="0.02" />
  <property name="wrist_roll_len" value="0.04" />


  <!-- wrist pitch link properties -->
  <property name="wrist_pitch_len" value="0.06" />
  <property name="wrist_pitch_width" value="0.04" />
  <property name="wrist_pitch_height" value="0.04" />

  <joint name="bottom_joint2" type="fixed">
    <origin xyz="0.15 0.07 0.38" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="base_link_2"/>
</joint>

<joint name="bottom_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="bottom_link"/>
  </joint>

  <link name="bottom_link">

    <visual>
      <origin xyz=" 0 0 -${base_link_height/2}"  rpy="0 0 0"/>
      <geometry>

         <box size="0.5 0.5 0.02" />

      </geometry>
      <material name="Brown" />
    </visual>

    <collision>
      <origin xyz=" 0 0 -0.04"  rpy="0 0 0"/>
      <geometry>
         <box size="1 1 0.02" />
      </geometry>
      </collision>>
      <xacro:inertial_matrix mass="100"/>
  </link>

  <gazebo reference="bottom_link">
    <material>Gazebo/White</material>
</gazebo>

<!-- BASE LINK -->
  <link name="base_link">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" /> <!-- rotate PI/2 -->
      <geometry>
	        <box size="${base_link_width} ${base_link_depth} ${base_link_height}" />
      </geometry>
      <material name="White"/>
    </visual>
  <collision>
      <origin xyz="0 0 0" rpy="0 0 0" /> <!-- rotate PI/2 -->
      <geometry>

         <box size="${base_link_width} ${base_link_depth} ${base_link_height}" />
    
      </geometry>
  </collision>

<!-- xacro:inertial_matrix mass="1" -->
</link>

<!-- BASE LINK -->
  <link name="base_link_2">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" /> 
      <geometry>
          <cylinder radius="0.04" length="${base_link2_height}"/>
      </geometry>
    <material name="White"/>
    </visual>
  <collision>
      <origin xyz="0 0 0" rpy="0 0 0" /> <!-- rotate PI/2 -->
      <geometry>
         <cylinder radius="0.04" length="${base_link2_height}"/>
      </geometry>
  </collision>
  <xacro:inertial_matrix mass="1"/>
</link>

<joint name="shoulder_pan_joint" type="revolute">
    <parent link="base_link_2"/>
    <child link="shoulder_pan_link"/>
    <origin xyz="0 0 0.02" rpy="0 0 -${M_PI}" />
    <axis xyz="0 0 1" />
    <limit effort="300" velocity="1" lower="-2.61799387799" upper="1.98394848567"/>
    <dynamics damping="50" friction="1"/>
</joint>

<!-- SHOULDER PAN LINK -->
  <link name="shoulder_pan_link" >

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>

            <cylinder radius="${shoulder_pan_width}" length="${shoulder_pan_len}"/>

      </geometry>
      <material name="Red"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
            <cylinder radius="${shoulder_pan_width}" length="${shoulder_pan_len}"/>
      </geometry>
    </collision>
<xacro:inertial_matrix mass="1"/>

</link>

  <joint name="shoulder_pitch_joint" type="revolute">
    <parent link="shoulder_pan_link"/>
    <child link="shoulder_pitch_link"/>
    <origin xyz="-0.041 0.0021 0.0" rpy="-${M_PI/2} 0 ${M_PI/2}" />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="-1.19962513147" upper="1.89994105047" />
    <dynamics damping="50" friction="1"/>
</joint>

<!-- SHOULDER PITCH LINK -->
  <link name="shoulder_pitch_link" >

    <visual>
      <origin xyz="-0.002 0 0.04" rpy="0 ${M_PI/2} 0" />
      <geometry>

           <box size="${shoulder_pitch_len} ${shoulder_pitch_width} ${shoulder_pitch_height}" />

      </geometry>
    <material name="Blue"/>
    </visual>

    <collision>
      <origin xyz="-0.002 0 0.04" rpy="0 ${M_PI/2} 0" />
      <geometry>
           <box size="${shoulder_pitch_len} ${shoulder_pitch_width} ${shoulder_pitch_height}" />
      </geometry>
    </collision>

    <xacro:inertial_matrix mass="1"/>

</link>

 <joint name="elbow_roll_joint" type="revolute">
    <parent link="shoulder_pitch_link"/>
    <child link="elbow_roll_link"/>
    <origin xyz="-0.002 0 0.1206" rpy="${M_PI} ${M_PI/2} 0" />
    <axis xyz="-1 0 0" />
    <limit effort="300" velocity="1" lower="-2.61799387799" upper="0.705631162427" />
    <dynamics damping="50" friction="1"/>
</joint>

<!-- ELBOW ROLL LINK -->
  <link name="elbow_roll_link" >

    <visual>
      <origin xyz="-0.015 0.0 -0.0" rpy="0 ${M_PI/2} 0" />
      <geometry>

            <cylinder radius= "${elbow_roll_width}" length="${elbow_roll_len}"/>

      </geometry>
   <material name="Red"/>
    </visual>

    <collision>
      <origin xyz="-0.015 0.0 -0.0" rpy="0 ${M_PI/2} 0" />
      <geometry>
            <cylinder radius="${elbow_roll_width}" length="${elbow_roll_len}"/>
      </geometry>
    </collision>

    <xacro:inertial_matrix mass="1"/>
</link>

<joint name="elbow_pitch_joint" type="revolute">
    <parent link="elbow_roll_link"/>
    <child link="elbow_pitch_link"/>
    <origin xyz="-0.035 0 0.0" rpy="${-M_PI/2} 0 0"/> <!-- 0.055--> 
    <axis xyz="0 1 0" />
    <limit effort="300" velocity="1" lower="-1.5953400194" upper="1.93281579274" />
    <dynamics damping="50" friction="1"/>
</joint>

<!-- ELBOW PITCH LINK -->
  <link name="elbow_pitch_link" >

    <visual>
      <origin xyz="0 0 -0.12" rpy="0 ${M_PI/2} 0" />
      <geometry>

       <box size="${elbow_pitch_len} ${elbow_pitch_width} ${elbow_pitch_height}" />
  
      </geometry>
    <material name="Blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 -0.12" rpy="0 ${M_PI/2} 0" />
      <geometry>
       <box size="${elbow_pitch_len} ${elbow_pitch_width} ${elbow_pitch_height}" />
      </geometry>
    </collision>
    <xacro:inertial_matrix mass="1"/>

</link>

<joint name="wrist_roll_joint" type="revolute">
    <parent link="elbow_pitch_link"/>
    <child link="wrist_roll_link"/>
    <origin xyz="0.0 0.0081 -.248" rpy="0 ${M_PI/2} ${M_PI}" />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="-2.61799387799" upper="2.6128806087" />
    <dynamics damping="50" friction="1"/>
</joint>

<link name="wrist_roll_link" >
    <visual>
      <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
           <cylinder radius="${wrist_roll_width}" length="${wrist_roll_len}"/>
      </geometry>
    <material name="Red"/>
    </visual>
  <collision>
      <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
           <cylinder radius="${wrist_roll_width}" length="${wrist_roll_len}"/>
      </geometry>
  </collision>
  <xacro:inertial_matrix mass="1"/>
</link>

<joint name="wrist_pitch_joint" type="revolute">
    <parent link="wrist_roll_link"/>
    <child link="wrist_pitch_link"/>
    <origin xyz="0.0 0.0 0.0001" rpy="0 ${M_PI/2} 0" />
    <axis xyz="1 0 0" />
    <limit effort="300" velocity="1" lower="-1.5953400194" upper="1.98394848567" />
    <dynamics damping="50" friction="1"/>
</joint>


<!-- WRIST PITCH LINK -->
  <link name="wrist_pitch_link">

    <visual>
      <origin xyz="0 0 0.04" rpy="0 ${M_PI/2} 0" />
      <geometry>

           <box size="${wrist_pitch_len} ${wrist_pitch_width} ${wrist_pitch_height}" />
  
      </geometry>
    <material name="Blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.04 " rpy="0 ${M_PI/2} 0" />
      <geometry>
          <box size="${wrist_pitch_len} ${wrist_pitch_width} ${wrist_pitch_height}" />
      </geometry>
    </collision>
    
    <xacro:inertial_matrix mass="1"/>

</link>

<xacro:include filename="$(find robotarm_description)/urdf/sensors/camera.urdf.xacro"/>
<!-- Initiate Transmission Tags for Each joint-->

   <xacro:transmission_block joint_name="shoulder_pan_joint"/>
   <xacro:transmission_block joint_name="shoulder_pitch_joint"/>
   <xacro:transmission_block joint_name="elbow_roll_joint"/>
   <xacro:transmission_block joint_name="elbow_pitch_joint"/>
   <xacro:transmission_block joint_name="wrist_roll_joint"/>
   <xacro:transmission_block joint_name="wrist_pitch_joint"/>

</robot>
